language: ruby

branches:
  except:
    - gh-pages

rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0

before_install:
  - pwd

  - sudo apt-get update
  - sudo apt-get install chromium-browser p7zip-full

  - wget -N http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip -P ~/Downloads
  - 7z e ~/Downloads/chromedriver_linux64.zip -y
  - ls
  - chmod +x chromedriver
  - sudo mv -f chromedriver /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
  - which chromedriver

  - firefox --version
  - phantomjs --version

  - gem update --system
  - gem --version
  - gem update

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - rake travis

script:
  - rake test:posts
  - rake test:ui